//
//  SizeOfControllerFont.h
//  Locoso
//
//  Created by yongchang hu on 12-1-17.
//  Copyright (c) 2012年 __MyCompanyName__. All rights reserved.
//

#ifndef Locoso_SizeOfControllerFont_h
#define Locoso_SizeOfControllerFont_h
//list size

#define SORTPRODUCTLISTVIEWCONTROLLER_LIST_HEIGHT 81
#define SORTPRODUCTLISTVIEWCONTROLLER_LIST_HEAD_SIZE 15
#define SORTPRODUCTLISTVIEWCONTROLLER_LIST_DETAIL_SIZE 12

#define SORTVIEWCONTROLLER_LIST_HEIGHT 44
#define SORTVIEWCONTROLLER_LIST_HEAD_SIZE 15
#define SORTVIEWCONTROLLER_LIST_DETAIL_SIZE 0

#define SORTNEXTPAGEVIEWCONTROLLER_LIST_HEIGHT 44
#define SORTNEXTPAGEVIEWCONTROLLER_LIST_HEAD_SIZE 15
#define SORTNEXTPAGEVIEWCONTROLLER_LIST_DETAIL_SIZE 0

#define SEARCHVIEWCONTROLLER_LIST_HEIGHT 44
#define SEARCHVIEWCONTROLLER_LIST_HEAD_SIZE 15
#define SEARCHVIEWCONTROLLER_LIST_DETAIL_SIZE 0

#define SEARCHRESULTVIEWCONTROLLER_LIST_HEIGHT 81
#define SEARCHRESULTVIEWCONTROLLER_LIST_HEAD_SIZE 15
#define SEARCHRESULTVIEWCONTROLLER_LIST_DETAIL_SIZE 0

#define COMPANYDETAILVIEWCONTROLLER_LIST_HEIGHT 81
#define COMPANYDETAILVIEWCONTROLLER_LIST_HEAD_SIZE 15
#define COMPANYDETAILVIEWCONTROLLER_LIST_DETAIL_SIZE 12

#define PRODUCTLISTVIEWCONTROLLER_LIST_HEIGHT 81
#define PRODUCTLISTVIEWCONTROLLER_LIST_HEAD_SIZE 15
#define PRODUCTLISTVIEWCONTROLLER_LIST_DETAIL_SIZE 12

#define NEWSLISTVIEWCONTROLLER_LIST_HEIGHT 44
#define NEWSLISTVIEWCONTROLLER_LIST_HEAD_SIZE 15
#define NEWSLISTVIEWCONTROLLER_LIST_DETAIL_SIZE 12

#define MYPRODUCTMANAGEVIEWCONTROLLER_LIST_HEIGHT 81
#define MYPRODUCTMANAGEVIEWCONTROLLER_LIST_HEAD_SIZE 15
#define MYPRODUCTMANAGEVIEWCONTROLLER_LIST_DETAIL_SIZE 12

#define MYNEWSMANAGEVIEWCONTROLLER_LIST_HEIGHT 44
#define MYNEWSMANAGEVIEWCONTROLLER_LIST_HEAD_SIZE 15
#define MYNEWSMANAGEVIEWCONTROLLER_LIST_DETAIL_SIZE 12

#define MYCOMPANYVIEWCONTROLLER_LIST_HEIGHT 43
#define MYCOMPANYVIEWCONTROLLER_LIST_HEAD_SIZE 17
#define MYCOMPANYVIEWCONTROLLER_LIST_DETAIL_SIZE 16

#define MOREVIEWCONTROLLER_LIST_HEAD_SIZE 17
#define MOREVIEWCONTROLLER_LIST_DETAIL_SIZE 15

#define SWITCHCITYVIEWCONTROLLER_LIST_HEAD_SIZE 15
#define SWITCHCITYVIEWCONTROLLER_LIST_DETAIL_SIZE 14

#define CHOOSECITYVIEWCONTROLLER_LIST_HEAD_SIZE 15
#define CHOOSECITYVIEWCONTROLLER_LIST_DETAIL_SIZE 14

#define MESSAGEMANAGEVIEWCONTROLLER_LIST_HEIGHT 115
//no list
#define PRODUCTDETAILVIEWCONTROLLER_HEAD_SIZE 16
#define PRODUCTDETAILVIEWCONTROLLER_BODY_SIZE 11

#define NEWSDETAILVIEWCONTROLLER_HEAD_SIZE 16
#define NEWSDETAILVIEWCONTROLLER_BODY_SIZE 11

//color
#define MYCOMPANYVIEWCONTROLLER_LIST_DETAIL_COLOR @"#f59b03"

//OTHER
#define SORTPRODUCTLISHTVIEWCONTROLLER_LIST_MAX_COUNT 10


#endif
